version: '3.8'

services:
  db:
    image: postgres:15
    container_name: authbackend-pg-container
    environment:
      POSTGRES_DB: authbackend-db
      POSTGRES_USER: danyfelipe
      POSTGRES_PASSWORD: hackerman
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authbackend-db
      SPRING_DATASOURCE_USERNAME: danyfelipe
      SPRING_DATASOURCE_PASSWORD: hackerman
    depends_on:
      - db

volumes:
  pgdata: